@startuml
hide members
!include contexts/orders/domain-objects.puml
!include contexts/orders/operation-stack.puml
!include contexts/logistics/domain-objects.puml
!include contexts/logistics/operation-stack.puml
!include contexts/logistics/plan-stock-transfer-links.puml

StockReservation }|-up-|| Order
OrderPosition -[hidden]down- Order

remove <<CommandOperation>>

@enduml