@startuml

!include ddd-style.puml
!include use-cases/cancel-order/use-case.puml
!include contexts/orders/operation-stack.puml
!include contexts/orders/domain-objects.puml
!include contexts/orders/cancel-order-links.puml

CancelOrderStep ..> CancelOrder
Order -[hidden]right- OrderPosition

remove $CreateOrder
hide <<ValueObject>> members
hide <<AggregateRootEntity>> members

OrdersContext.DomainObjects .[hidden]down. OrdersContext.OperationStack

CancelOrderStep <<SelectedUseCaseStep>>

@enduml
